logger:
  level: trace
  log: /var/log/byconity/tso.log
  errorlog: /var/log/byconity/tso.err.log
  testlog: /var/log/byconity/tso.test.log
  size: 1000M
  count: 10
  console: true
listen_host: "::"
path: /var/byconity/tso
tmp_path: /var/byconity/tmp
service_discovery:
  mode: dns
  cluster: default
tso_service:
  type: fdb
  fdb:
    cluster_file: /etc/byconity/fdb/cluster-file
  port: 9000
  http:
    port: 8123
    receive_timeout: 1800
    send_timeout: 1800
  tso_window_ms: 3000
  tso_get_leader_info_interval_ms: 0
