apiVersion: v1
kind: Service
metadata:
  name: {{ include "byconity.fullname" . }}-daemon-manager
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: daemon-manager
spec:
  type: ClusterIP
  selector:
    {{- include "byconity.selectorLabels" . | nindent 4 }}
    byconity-role: daemon-manager
  ports:
    - name: port0
      port: 9000
      targetPort: tcp

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "byconity.fullname" . }}-daemon-manager-headless
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: daemon-manager
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "byconity.selectorLabels" . | nindent 4 }}
    byconity-role: daemon-manager
  ports:
    - name: port0
      port: 9000
      targetPort: tcp
