apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byconity.fullname" . }}-dm-run
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: daemon-manager
data:
  run: |
    #!/bin/bash
    exec "${APP_ROOT}/bin/daemon-manager" --config "/etc/byconity/daemon-manager.yaml"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byconity.fullname" . }}-dm-config
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: daemon-manager
data:
  daemon-manager.yaml: |
    {{- $server_service := dict "service" (printf "%s-%s" .Release.Name "server") "headless_service" (printf "%s-%s-headless" .Release.Name "server") "psm" (printf "%s-%s" .Release.Name "server") }}
    {{- $tso_service := dict "service" (printf "%s-%s" .Release.Name "tso") "headless_service" (printf "%s-%s-headless" .Release.Name "tso") "psm" (printf "%s-%s" .Release.Name "tso") }}
    {{- $service_discovery := dict "service_discovery" (dict "server" $server_service "tso" $tso_service) }}
    {{- .Files.Get "files/daemon-manager.yaml" | fromYaml | merge .Values.byconity.daemonManager.configOverwrite $.Values.byconity.configOverwrite $service_discovery | toYaml | nindent 4 }}
  hdfs3.xml: |
    <configuration>
        {{- range $key, $val := $.Values.byconity.hdfs3Config }}
        <property>
            <name>{{ $key }}</name>
            <value>{{ $val }}</value>
        </property>
        {{- end }}
    </configuration>
  cnch-config.yaml: |
    {{- $ports := dict "tcp_port" .Values.byconity.ports.tcp "http_port" .Values.byconity.ports.http "rpc_port" .Values.byconity.ports.rpc "exchange_port" .Values.byconity.ports.exchange "exchange_status_port" .Values.byconity.ports.exchangeStatus }}
    {{- $server_service := dict "service" (printf "%s-%s" .Release.Name "server") "headless_service" (printf "%s-%s-headless" .Release.Name "server") "psm" (printf "%s-%s" .Release.Name "server") }}
    {{- $tso_service := dict "service" (printf "%s-%s" .Release.Name "tso") "headless_service" (printf "%s-%s-headless" .Release.Name "tso") "psm" (printf "%s-%s" .Release.Name "tso") }}
    {{- $dm_service := dict "service" (printf "%s-%s" .Release.Name "daemon-manager") "headless_service" (printf "%s-%s-headless" .Release.Name "daemon-manager") "psm" (printf "%s-%s" .Release.Name "daemon-manager") }}
    {{- $rm_service := dict "service" (printf "%s-%s" .Release.Name "resource-manager") "headless_service" (printf "%s-%s-headless" .Release.Name "resource-manager") "psm" (printf "%s-%s" .Release.Name "resource-manager") }}
    {{- $service_discovery := dict "service_discovery" (dict "server" $server_service "tso" $tso_service "daemon_manager" $dm_service "resource_manager" $rm_service) }}
    {{- $catalog := dict "catalog" (dict "name_space" (include "byconity.fullname" .)) }}
    {{- $hdfs_addr := dict "hdfs_addr" .Values.byconity.hdfs_address }}
    {{- .Files.Get "files/cnch-config.yaml" | fromYaml | merge  $hdfs_addr $catalog $service_discovery $ports | toYaml | nindent 4 }}

