apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byconity.fullname" . }}-lifecycle
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: server
data:
  poststart: |
    #!/bin/bash
    set -eo pipefail
    {{- .Values.byconity.postStart | nindent 4}}
  prestop: |-
    #!/bin/bash
    set -eo pipefail
    if [[ "${BYCONITY_ROLE}" == "worker" ]]; then
      curl --fail -X GET "http://127.0.0.1:{{ .Values.byconity.ports.http }}/api/resource_report?action=stop"
    fi
    {{- .Values.byconity.preStop | nindent 4 }}
  readiness: |
    #!/bin/bash
    set -euo pipefail
    QUERY_TIMEOUT=5
    timeout -k 1 "${QUERY_TIMEOUT}" clickhouse-client -h 127.0.0.1 --port "{{ .Values.byconity.ports.tcp }}" --user "probe" --password "{{ .Values.byconity.usersOverwrite.users.probe.password }}" --max_execution_time "$((QUERY_TIMEOUT-1))" -n -q "select 1" 2>&1
    {{- .Values.byconity.readiness | nindent 4}}
  liveness: |
    #!/bin/bash
    {{- .Values.byconity.liveness | nindent 4 }}
  readiness-tso: |
    #!/bin/bash
    set -euo pipefail
    curl --connect-timeout 3 --fail http://localhost:9000/health
    {{- .Values.byconity.readiness | nindent 4}}
  liveness-tso: |
    #!/bin/bash
  readiness-dm: |
    #!/bin/bash
    set -euo pipefail
    curl --connect-timeout 3 --fail http://localhost:9000/health
    {{- .Values.byconity.readiness | nindent 4}}
  liveness-dm: |
    #!/bin/bash
  readiness-rm: |
    #!/bin/bash
    set -euo pipefail
    curl --connect-timeout 3 --fail http://localhost:9000/health
    {{- .Values.byconity.readiness | nindent 4}}
  liveness-rm: |
    #!/bin/bash
{{- range $key, $data := .Values.byconity.lifecycleExtraConfig }}
  {{ $key | quote }}: {{ $data | quote }}
{{- end }}
