apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byconity.fullname" . }}-rm-run
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: resource-manager
data:
  run: |
    #!/bin/bash
    exec "${APP_ROOT}/bin/resource-manager" --config "/etc/byconity/resource-manager.yaml"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byconity.fullname" . }}-rm-config
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: resource-manager
data:
  resource-manager.yaml: |
    {{- .Files.Get "files/resource-manager.yaml" | fromYaml | merge .Values.byconity.resourceManager.configOverwrite | toYaml | nindent 4 }}
