apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byconity.fullname" . }}-tso-run
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: tso
data:
  run: |
    #!/bin/bash
    exec "${APP_ROOT}/bin/tso-server" --config "/etc/byconity/tso.yaml"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byconity.fullname" . }}-tso-config
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: tso
data:
  tso.yaml: |
    {{- $tso_service := dict "service" (printf "%s-%s" .Release.Name "tso") "headless_service" (printf "%s-%s-headless" .Release.Name "tso") "psm" (printf "%s-%s" .Release.Name "tso") }}
    {{- $service_discovery := dict "service_discovery" (dict "tso" $tso_service) }}
    {{- .Files.Get "files/tso.yaml" | fromYaml | merge .Values.byconity.tso.configOverwrite $service_discovery | toYaml | nindent 4 }}
