apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byconity.fullname" . }}-tso-run
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: tso
data:
  run: |
    #!/bin/bash
    exec "${APP_ROOT}/bin/tso-server" --config "/etc/byconity/tso.yaml"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "byconity.fullname" . }}-tso-config
  labels:
    {{- include "byconity.labels" . | nindent 4 }}
    byconity-role: tso
data:
  tso.yaml: |
    {{- .Files.Get "files/tso.yaml" | fromYaml | merge .Values.byconity.tso.configOverwrite | toYaml | nindent 4 }}
