byconity:
  image: byconity/byconity:0.1.0-beta

  server:
    replicas: 1
    securityContext:
      capabilities:
        add:
          - SYS_PTRACE
    storage:
      localDisk:
        pvcSpec:
          storageClassName: standard
      log:
        pvcSpec:
          storageClassName: standard
    configOverwrite:
      timezone: Asia/Shanghai

  tso:
    replicas: 1

  daemonManager:
    replicas: 1

  resourceManager:
    replicas: 1

  defaultWorker: &defaultWorker
    replicas: 1
    podAnnotations: {}
    resources: {}
    hostNetwork: false
    nodeSelector: {}
    tolerations: []
    affinity: {}
    imagePullSecrets: []
    securityContext: {}
    storage:
      localDisk:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Gi
          storageClassName: standard
      log:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: standard
    configOverwrite:
      logger:
        level: trace
      disk_cache_strategies:
        simple:
          lru_max_size: 429496729600 # 400Gi
      timezone: Asia/Shanghai
    hdfs3Config:
      dfs.client.metrics.enable: true
      dfs.client.metrics.use_domain_socket: true
      dfs.default.blocksize: "268435456"
      dfs.read.hedge_read.interval_ms: 120
      input.connect.timeout: 10000
      input.read.max.retry: 3
      input.read.timeout: 6000
      input.write.timeout: 10000
      output.close.timeout: 256000
      output.connect.timeout: 10000
      output.default.write.retry: 3
      output.read.timeout: 120000
      output.write.timeout: 256000
      rpc.client.connect.retry: 3
      rpc.client.connect.timeout: 10000
      rpc.client.read.timeout: 20000
      rpc.client.timeout: 20000
      rpc.client.write.timeout: 20000

  virtualWarehouses:
    - <<: *defaultWorker
      name: vw_default
      replicas: 1
    - <<: *defaultWorker
      name: vw_write
      replicas: 1

fdb:
  clusterSpec:
    processCounts:
      stateless: 1
      log: 3

hdfs:
  enabled: true
  namenode:
    dataVolumes:
      count: 1
      pvcTemplateSpec:
        storageClassName: standard
  datanode:
    nodeCount: 1
    dataVolumes:
      count: 1
      pvcTemplateSpec:
        storageClassName: standard
