byconity:
  image: byconity/byconity:stable

  server:
    replicas: 1
    securityContext:
      capabilities:
        add:
          - SYS_PTRACE
    storage:
      localDisk:
        pvcSpec:
          storageClassName: standard
          resources:
            requests:
              storage: 10Gi
      log:
        pvcSpec:
          storageClassName: standard
          resources:
            requests:
              storage: 10Gi
    configOverwrite:
      timezone: Asia/Shanghai

  tso:
    replicas: 1
    storage:
      localDisk:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: standard #replace to your storageClassName
      log:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: standard #replace to your storageClassName

  daemonManager:
    replicas: 1

  resourceManager:
    replicas: 1

  defaultWorker: &defaultWorker
    replicas: 1
    podAnnotations: {}
    resources: {}
    hostNetwork: false
    nodeSelector: {}
    tolerations: []
    affinity: {}
    imagePullSecrets: []
    securityContext: {}
    storage:
      localDisk:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: standard
      log:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: standard
    configOverwrite:
      logger:
        level: trace
      disk_cache_strategies:
        simple:
          lru_max_size: 429496729600 # 400Gi
      timezone: Asia/Shanghai

  virtualWarehouses:
    - <<: *defaultWorker
      name: vw_default
      replicas: 1
    - <<: *defaultWorker
      name: vw_write
      replicas: 1
fdb-operator:
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 1
      memory: 512Mi
  image:
    repository: foundationdb/fdb-kubernetes-operator
    tag: v1.9.0
    pullPolicy: IfNotPresent
fdb:
  clusterSpec:
    processCounts:
      stateless: 1
      log: 3
      storage: 3
    processes:
      general:
        volumeClaimTemplate:
          spec:
            storageClassName: standard #replace to your storageClassName
            resources:
              requests:
                storage: 10Gi

hdfs:
  enabled: true
  namenode:
    dataVolumes:
      count: 1
      pvcTemplateSpec:
        storageClassName: standard
  datanode:
    nodeCount: 1
    dataVolumes:
      count: 1
      pvcTemplateSpec:
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
