
image:
  repository: byconity/byconity
  tag: stable
  imagePullPolicy: IfNotPresent

byconity:
  server:
    replicas: 2
    securityContext:
      capabilities:
        add:
          - SYS_PTRACE
    storage:
      localDisk:
        pvcSpec:
          storageClassName: standard
          resources:
            requests:
              storage: 10Gi
      log:
        pvcSpec:
          storageClassName: standard
          resources:
            requests:
              storage: 10Gi
    configOverwrite:
      timezone: Asia/Shanghai
    livenessProbe:
      exec:
        command: ["/opt/byconity/scripts/lifecycle/liveness"]
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 20
    readinessProbe:
      exec:
        command: ["/opt/byconity/scripts/lifecycle/readiness"]
      failureThreshold: 5
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

  tso:
    replicas: 3
    image: ""
    podAnnotations: { }
    resources:
      limits:
        cpu: "3"  # >=3
        memory: 2Gi
      requests:
        cpu: "3"  # >=3
        memory: 2Gi
    storage:
      localDisk:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi
          storageClassName: standard #replace to your storageClassName
      log:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: standard #replace to your storageClassName

  daemonManager:
    replicas: 1

  resourceManager:
    replicas: 2

  defaultWorker: &defaultWorker
    replicas: 1
    podAnnotations: {}
    resources: {}
    hostNetwork: false
    nodeSelector: {}
    tolerations: []
    affinity: {}
    imagePullSecrets: []
    securityContext: {}
    storage:
      localDisk:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: standard
      log:
        pvcSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: standard
    configOverwrite:
      logger:
        level: trace
      disk_cache_strategies:
        simple:
          lru_max_size: 429496729600 # 400Gi
      timezone: Asia/Shanghai

  virtualWarehouses:
    - <<: *defaultWorker
      name: vw_default
      replicas: 1
    - <<: *defaultWorker
      name: vw_write
      replicas: 1
fdb-operator:
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 1
      memory: 512Mi
  image:
    repository: foundationdb/fdb-kubernetes-operator
    tag: v1.9.0
    pullPolicy: IfNotPresent
  initContainers:
    6.2:
      image:
        repository: foundationdb/foundationdb-kubernetes-sidecar
        tag: 6.2.30-1
        pullPolicy: IfNotPresent
    6.3:
      image:
        repository: foundationdb/foundationdb-kubernetes-sidecar
        tag: 6.3.23-1
        pullPolicy: IfNotPresent
    7.1:
      image:
        repository: foundationdb/foundationdb-kubernetes-sidecar
        tag: 7.1.15-1
        pullPolicy: IfNotPresent
fdb:
  clusterSpec:
    processCounts:
      stateless: 1
      log: 3
      storage: 3
    processes:
      general:
        volumeClaimTemplate:
          spec:
            storageClassName: standard #replace to your storageClassName
            resources:
              requests:
                storage: 10Gi

hdfs:
  enabled: true
  alpine:
    repository: alpine  #if your machine is amd64.please use amd64/alpine
    tag: 3.10.2
    imagePullPolicy: IfNotPresent
  namenode:
    dataVolumes:
      count: 1
      pvcTemplateSpec:
        storageClassName: standard
  datanode:
    nodeCount: 1
    dataVolumes:
      count: 1
      pvcTemplateSpec:
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
